### PR TITLE
Loops

### PR DESCRIPTION
**Pull request by yofukashino**
Added Options in Loop Like if you want to Loop The Whole Queue or just the Current song. (*￣3￣)╭

### CODE REVIEW

**Comment by Allvaa** [comment]
i'll review soon

**Comment by yofukashino** [comment]
> i'll review soon

Thanks Senpai

**Review by Allvaa — CHANGES_REQUESTED** [review]
i'd rather if it doesn't delete the bot's messages and without footer and timestamp

**Review by Allvaa — APPROVED** [review]
nevermind about the change req, i can change it by myself later

**Pull request merged**
