### PR TITLE
feat(Timeout Leave): Set Timeout to leave voice channel

### PR DESCRIPTION
**Pull request by lxndr-rl**
#63

### CODE REVIEW

**Comment by Allvaa** [comment]
i will review later 👍

**Review by Allvaa — COMMENTED** [review]
i thought you're working on the "will leave from the vc when only bot in the vc". your pr just add a timeout to leave when queue empty, but ok. are you gonna working on that? if not I'll merge this now

**Comment by lxndr-rl** [comment]
ohhh, I hadn't understood that.  don't Merge

**Comment by Allvaa** [comment]
alright

**Comment by Allvaa** [comment]
should i close this PR @lxndr-rl ?

**Comment by lxndr-rl** [comment]
I will open another PR applying this and the other feat

**Pull request closed without merging**
