### PR TITLE
Fixed Unknown Interaction in Pagination (util.js)

### PR DESCRIPTION
**Pull request by Abdul1810**
This will Fix The Unknown Interaction Error From RequestHandler.js.So, Merge This PR.

### CODE REVIEW

**Comment by yofukashino** [comment]
me who just added   
 ```
process.on("unhandledRejection", error => {
            if (error.code == "10008" || error.code == "10062") return;
            this.logger.error(error.stack);
        });
```
To my code be like okay

**Comment by yofukashino** [comment]
I just ignores both of the errors. unknown interaction and unknown message. :')

**Comment by Abdul1810** [comment]
Ok Ty.

**Comment by Allvaa** [comment]
wondering if is that code change will affect it. as far as I know, Unknown Interaction error would appear when you don't give respond to the interaction in 3 seconds, and after the 3s it becomes invalid, when you try to respond to the interaction, it will throw Unknown Interaction.

internet connection matters I guess

**Pull request closed without merging**
