### PR TITLE
Update util.js

### PR DESCRIPTION
**Pull request by rajamoulimallareddy**

### CODE REVIEW

**Comment by Allvaa** [comment]
is there any reason to put the if statement in there?

**Comment by rajamoulimallareddy** [comment]
> is there any reason to put the if statement in there?

yes cause I tried removing it and clicked on a button it just disables the button only after a single click

**Comment by yofukashino** [comment]
Well you can disable that single click issue by removing max from collector itself also

**Comment by rajamoulimallareddy** [comment]
> Well you can disable that single click issue by removing max from collector itself also

tried but still the same

**Comment by yofukashino** [comment]
well this is  ```
static get paginationEmojis() {
        return ["⏮", "◀", "⛔", "▶", "⏭"];
    }

    static async pagination(msg, author, contents, currPage = 0) {
        /** @type {import("discord.js").InteractionCollector} */
        const collector = msg.createMessageComponentCollector({
            filter: interaction => this.paginationEmojis.includes(interaction.customId) && interaction.user.id === author.id,
            componentType: "BUTTON",
            time: 30000
        });

        collector
            .on("collect", async (interaction) => {
                await interaction.deferUpdate();
                const emoji = interaction.customId;
                if (emoji === this.paginationEmojis[0]) (currPage = 0);
                if (emoji === this.paginationEmojis[1]) currPage--;
                if (emoji === this.paginationEmojis[2]) {
                    await interaction.editReply({ components: [new MessageActionRow().addComponents(...interaction.message.components[0].components.map(x => x.setDisabled(true)))] });
                    return;
                }
                if (emoji === this.paginationEmojis[3]) currPage++;
                if (emoji === this.paginationEmojis[4]) (currPage = (contents.length - 1));
                currPage = ((currPage % contents.length) + contents.length) % contents.length;
                const embed = interaction.message.embeds[0]
                    .setDescription(contents[currPage])
                    .setFooter(`Page ${currPage + 1} of ${contents.length}.`);
                await interaction.editReply({ embeds: [embed] });
                this.pagination(msg, author, contents, currPage);
            } 
            )
            .on("end", () => {
                msg.edit({ components: [new MessageActionRow().addComponents(...msg.components[0].components.map(x => x.setDisabled(true)))] });
            });
    }
```
    Working Fine for me

**Review by Allvaa — APPROVED** [review]

**Pull request merged**
