### PR TITLE
update

### PR DESCRIPTION
**Pull request by yofukashino**
will reply with prefix if mentions bot and command cooldown if you add a timeout property to command else it wouldnt activate

### CODE REVIEW

**Comment by yofukashino** [comment]
#115 covered in this you can close that one

**Comment by Allvaa** [comment]
> will reply with prefix if mentions bot and command cooldown if you add a timeout property to command else it wouldnt activate

I think the property name should be cooldown instead

**Comment by Allvaa** [comment]
also in what time unit is the cooldown tho

**Comment by yofukashino** [comment]
it would be milliseconds

**Pull request closed without merging**
