### PR TITLE
Playlist identifier corrected

### PR DESCRIPTION
**Pull request by yofukashino**
well it is what it is

### CODE REVIEW

**Comment by Allvaa** [comment]
https://deivu.github.io/Shoukaku/?api#ShoukakuTrackList#type

**Comment by yofukashino** [comment]
Well using it as you wrote it. It was just adding the first song of Playlist to queue and not detecting link as Playlist but changing this makes it work for me. I was testing with my spotify [Playlist]( https://open.spotify.com/playlist/7cQNX8C8gw7GhCGtigPez9?si=_GXMbo1yQa6qXX3W73uK-w&utm_source=copy-link&dl_branch=1)

**Comment by Allvaa** [comment]
well it only breaks non-spotify playlists while it fixes spotify playlists

we can wrap the load type from lavasfy like shoukaku does to fix both https://github.com/Deivu/Shoukaku/blob/master/src/struct/ShoukakuTrackList.js

**Comment by Allvaa** [comment]
> well it only breaks non-spotify playlists while it fixes spotify playlists
> 
> we can wrap the load type from lavasfy like shoukaku does to fix both https://github.com/Deivu/Shoukaku/blob/master/src/struct/ShoukakuTrackList.js

@Tharki-God wanna do it? if not I'm gonna do it myself

**Comment by yofukashino** [comment]
idk how to do that

**Comment by yofukashino** [comment]
okay whatever this fix is way easier.

**Review by Allvaa — APPROVED** [review]

**Pull request merged**
